# flux-nginx-demo/helmrelease.yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: nginx
  namespace: my-app
spec:
  interval: 1m
  url: git@github.com:abhijithvg/flux-nginx-demo.git
  ref:
    branch: main

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: my-app
spec:
  releaseName: nginx
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: GitRepository
        name: nginx
        namespace: my-app
      version: 1.0.0
  values:
    image:
      repository: nginx
      tag: "1.21.6"  # Update the version here
      pullPolicy: Always  # Ensure the image is pulled every time
    service:
      enabled: true
      type: LoadBalancer
