# flux-nginx-demo/helmrelease.yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: nginx
  namespace: default
spec:
  interval: 1m
  url: ssh://git@github.com/abhijithvg/flux-nginx-demo
  ref:
    branch: main

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  releaseName: nginx
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: GitRepository
        name: nginx
        namespace: default
      version: 15.1.0 # Ensure this is the right version of the chart
  values:
    image:
      repository: nginx
      tag: "1.25.1"  # Update the version here
      pullPolicy: Always  # Ensure the image is pulled every time
    service:
      enabled: true
      type: LoadBalancer
