apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: my-app
  namespace: flux-system # This should be the namespace where Flux operates
spec:
  interval: 1m
  path: "./"
  prune: true
  sourceRef:
    kind: GitRepository
    name: nginx
    namespace: my-app
  resources:
    - helmrelease.yaml
